version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: filehive_postgres
    environment:
      POSTGRES_USER: filehive
      POSTGRES_PASSWORD: filehivepass
      POSTGRES_DB: filehive_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: filehive_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
